meta_product_name: "Booker"
meta_title: "Booker - Share book with your friends and family for free"
meta_description: "With Booker.ovh you can share your book library with your friends and family. This allows you to ask them for a book to read!"
meta_image: "cover.png"
twitter_account: "@OvhBooker"
